version: '3.8'
services:
  mochmatch-devcontainer:
    build:
      context: .
      dockerfile: flutter/Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    env_file:
      - flutter/.flutter.env
